//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.BPEL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartPayment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.BPEL.ItemPayment[] itemsField;
        
        private long buyerIdField;
        
        private double amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authTokenField;
        
        private bool productsAvailableField;
        
        private bool successfulPaymentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsoleApplication1.BPEL.ItemPayment[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long buyerId {
            get {
                return this.buyerIdField;
            }
            set {
                if ((this.buyerIdField.Equals(value) != true)) {
                    this.buyerIdField = value;
                    this.RaisePropertyChanged("buyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string authToken {
            get {
                return this.authTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.authTokenField, value) != true)) {
                    this.authTokenField = value;
                    this.RaisePropertyChanged("authToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool productsAvailable {
            get {
                return this.productsAvailableField;
            }
            set {
                if ((this.productsAvailableField.Equals(value) != true)) {
                    this.productsAvailableField = value;
                    this.RaisePropertyChanged("productsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool successfulPayment {
            get {
                return this.successfulPaymentField;
            }
            set {
                if ((this.successfulPaymentField.Equals(value) != true)) {
                    this.successfulPaymentField = value;
                    this.RaisePropertyChanged("successfulPayment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPayment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ItemPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long productIdField;
        
        private int unitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                if ((this.unitsField.Equals(value) != true)) {
                    this.unitsField = value;
                    this.RaisePropertyChanged("units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://orderws.unisell.miw.uniovi/")]
    public partial class PaymentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://orderws.unisell.miw.uniovi/")]
    public partial class itemOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long productIdField;
        
        private bool productIdFieldSpecified;
        
        private int unitsField;
        
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("units");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("unitsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://orderws.unisell.miw.uniovi/")]
    public partial class shoppingCartOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountField;
        
        private bool amountFieldSpecified;
        
        private string authTokenField;
        
        private long buyerIdField;
        
        private bool buyerIdFieldSpecified;
        
        private itemOrder[] itemsField;
        
        private string passwordField;
        
        private bool productsAvailableField;
        
        private string signatureField;
        
        private bool successfulPaymentField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("authToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long buyerId {
            get {
                return this.buyerIdField;
            }
            set {
                this.buyerIdField = value;
                this.RaisePropertyChanged("buyerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyerIdSpecified {
            get {
                return this.buyerIdFieldSpecified;
            }
            set {
                this.buyerIdFieldSpecified = value;
                this.RaisePropertyChanged("buyerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public itemOrder[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool productsAvailable {
            get {
                return this.productsAvailableField;
            }
            set {
                this.productsAvailableField = value;
                this.RaisePropertyChanged("productsAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool successfulPayment {
            get {
                return this.successfulPaymentField;
            }
            set {
                this.successfulPaymentField = value;
                this.RaisePropertyChanged("successfulPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class itemAvail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long productIdField;
        
        private bool productIdFieldSpecified;
        
        private int unitsField;
        
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("units");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("unitsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class shoppingCartAvail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountField;
        
        private bool amountFieldSpecified;
        
        private string authTokenField;
        
        private long buyerIdField;
        
        private bool buyerIdFieldSpecified;
        
        private itemAvail[] itemsField;
        
        private string passwordField;
        
        private bool productsAvailableField;
        
        private string signatureField;
        
        private bool successfulPaymentField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("authToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long buyerId {
            get {
                return this.buyerIdField;
            }
            set {
                this.buyerIdField = value;
                this.RaisePropertyChanged("buyerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyerIdSpecified {
            get {
                return this.buyerIdFieldSpecified;
            }
            set {
                this.buyerIdFieldSpecified = value;
                this.RaisePropertyChanged("buyerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public itemAvail[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool productsAvailable {
            get {
                return this.productsAvailableField;
            }
            set {
                this.productsAvailableField = value;
                this.RaisePropertyChanged("productsAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool successfulPayment {
            get {
                return this.successfulPaymentField;
            }
            set {
                this.successfulPaymentField = value;
                this.RaisePropertyChanged("successfulPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://orderws.unisell.miw.uniovi/")]
    public partial class ArgumentExceptionOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ProductNotAvailableException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.Invocation.tps", ConfigurationName="BPEL.WS_Invocation")]
    public interface WS_Invocation {
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.Invocation.tps/process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.BPEL.processResponse process(ConsoleApplication1.BPEL.processRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.Invocation.tps/process", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.processResponse> processAsync(ConsoleApplication1.BPEL.processRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.Invocation.tps")]
    public partial class WS_InvocationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private shoppingCartAvail inputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public shoppingCartAvail input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("input");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.Invocation.tps")]
    public partial class WS_InvocationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.Invocation.tps", Order=0)]
        public ConsoleApplication1.BPEL.WS_InvocationRequest WS_InvocationRequest;
        
        public processRequest() {
        }
        
        public processRequest(ConsoleApplication1.BPEL.WS_InvocationRequest WS_InvocationRequest) {
            this.WS_InvocationRequest = WS_InvocationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.Invocation.tps", Order=0)]
        public ConsoleApplication1.BPEL.WS_InvocationResponse WS_InvocationResponse;
        
        public processResponse() {
        }
        
        public processResponse(ConsoleApplication1.BPEL.WS_InvocationResponse WS_InvocationResponse) {
            this.WS_InvocationResponse = WS_InvocationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_InvocationChannel : ConsoleApplication1.BPEL.WS_Invocation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_InvocationClient : System.ServiceModel.ClientBase<ConsoleApplication1.BPEL.WS_Invocation>, ConsoleApplication1.BPEL.WS_Invocation {
        
        public WS_InvocationClient() {
        }
        
        public WS_InvocationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_InvocationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InvocationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InvocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.BPEL.processResponse ConsoleApplication1.BPEL.WS_Invocation.process(ConsoleApplication1.BPEL.processRequest request) {
            return base.Channel.process(request);
        }
        
        public ConsoleApplication1.BPEL.WS_InvocationResponse process(ConsoleApplication1.BPEL.WS_InvocationRequest WS_InvocationRequest) {
            ConsoleApplication1.BPEL.processRequest inValue = new ConsoleApplication1.BPEL.processRequest();
            inValue.WS_InvocationRequest = WS_InvocationRequest;
            ConsoleApplication1.BPEL.processResponse retVal = ((ConsoleApplication1.BPEL.WS_Invocation)(this)).process(inValue);
            return retVal.WS_InvocationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.processResponse> ConsoleApplication1.BPEL.WS_Invocation.processAsync(ConsoleApplication1.BPEL.processRequest request) {
            return base.Channel.processAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.BPEL.processResponse> processAsync(ConsoleApplication1.BPEL.WS_InvocationRequest WS_InvocationRequest) {
            ConsoleApplication1.BPEL.processRequest inValue = new ConsoleApplication1.BPEL.processRequest();
            inValue.WS_InvocationRequest = WS_InvocationRequest;
            return ((ConsoleApplication1.BPEL.WS_Invocation)(this)).processAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BPEL.PaymentWSSoap")]
    public interface PaymentWSSoap {
        
        // CODEGEN: Generating message contract since element name orderDetails from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        ConsoleApplication1.BPEL.PayResponse Pay(ConsoleApplication1.BPEL.PayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.PayResponse> PayAsync(ConsoleApplication1.BPEL.PayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pay", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.BPEL.PayRequestBody Body;
        
        public PayRequest() {
        }
        
        public PayRequest(ConsoleApplication1.BPEL.PayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.BPEL.ShoppingCartPayment orderDetails;
        
        public PayRequestBody() {
        }
        
        public PayRequestBody(ConsoleApplication1.BPEL.ShoppingCartPayment orderDetails) {
            this.orderDetails = orderDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.BPEL.PayResponseBody Body;
        
        public PayResponse() {
        }
        
        public PayResponse(ConsoleApplication1.BPEL.PayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.BPEL.ShoppingCartPayment PayResult;
        
        public PayResponseBody() {
        }
        
        public PayResponseBody(ConsoleApplication1.BPEL.ShoppingCartPayment PayResult) {
            this.PayResult = PayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentWSSoapChannel : ConsoleApplication1.BPEL.PaymentWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentWSSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.BPEL.PaymentWSSoap>, ConsoleApplication1.BPEL.PaymentWSSoap {
        
        public PaymentWSSoapClient() {
        }
        
        public PaymentWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.BPEL.PayResponse ConsoleApplication1.BPEL.PaymentWSSoap.Pay(ConsoleApplication1.BPEL.PayRequest request) {
            return base.Channel.Pay(request);
        }
        
        public ConsoleApplication1.BPEL.ShoppingCartPayment Pay(ConsoleApplication1.BPEL.ShoppingCartPayment orderDetails) {
            ConsoleApplication1.BPEL.PayRequest inValue = new ConsoleApplication1.BPEL.PayRequest();
            inValue.Body = new ConsoleApplication1.BPEL.PayRequestBody();
            inValue.Body.orderDetails = orderDetails;
            ConsoleApplication1.BPEL.PayResponse retVal = ((ConsoleApplication1.BPEL.PaymentWSSoap)(this)).Pay(inValue);
            return retVal.Body.PayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.PayResponse> ConsoleApplication1.BPEL.PaymentWSSoap.PayAsync(ConsoleApplication1.BPEL.PayRequest request) {
            return base.Channel.PayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.BPEL.PayResponse> PayAsync(ConsoleApplication1.BPEL.ShoppingCartPayment orderDetails) {
            ConsoleApplication1.BPEL.PayRequest inValue = new ConsoleApplication1.BPEL.PayRequest();
            inValue.Body = new ConsoleApplication1.BPEL.PayRequestBody();
            inValue.Body.orderDetails = orderDetails;
            return ((ConsoleApplication1.BPEL.PaymentWSSoap)(this)).PayAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://orderws.unisell.miw.uniovi/", ConfigurationName="BPEL.ICreateOrderWS")]
    public interface ICreateOrderWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrderRequest", ReplyAction="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.BPEL.PaymentException), Action="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrder/Fault/PaymentExcepti" +
            "on", Name="PaymentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.BPEL.ArgumentExceptionOrder), Action="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrder/Fault/ArgumentExcept" +
            "ionOrder", Name="ArgumentExceptionOrder")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.BPEL.createOrderResponse createOrder(ConsoleApplication1.BPEL.createOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrderRequest", ReplyAction="http://orderws.unisell.miw.uniovi/ICreateOrderWS/createOrderResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.createOrderResponse> createOrderAsync(ConsoleApplication1.BPEL.createOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrder", WrapperNamespace="http://orderws.unisell.miw.uniovi/", IsWrapped=true)]
    public partial class createOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://orderws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.BPEL.shoppingCartOrder arg0;
        
        public createOrderRequest() {
        }
        
        public createOrderRequest(ConsoleApplication1.BPEL.shoppingCartOrder arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrderResponse", WrapperNamespace="http://orderws.unisell.miw.uniovi/", IsWrapped=true)]
    public partial class createOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://orderws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public createOrderResponse() {
        }
        
        public createOrderResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateOrderWSChannel : ConsoleApplication1.BPEL.ICreateOrderWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateOrderWSClient : System.ServiceModel.ClientBase<ConsoleApplication1.BPEL.ICreateOrderWS>, ConsoleApplication1.BPEL.ICreateOrderWS {
        
        public CreateOrderWSClient() {
        }
        
        public CreateOrderWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateOrderWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateOrderWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateOrderWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.BPEL.createOrderResponse ConsoleApplication1.BPEL.ICreateOrderWS.createOrder(ConsoleApplication1.BPEL.createOrderRequest request) {
            return base.Channel.createOrder(request);
        }
        
        public string createOrder(ConsoleApplication1.BPEL.shoppingCartOrder arg0) {
            ConsoleApplication1.BPEL.createOrderRequest inValue = new ConsoleApplication1.BPEL.createOrderRequest();
            inValue.arg0 = arg0;
            ConsoleApplication1.BPEL.createOrderResponse retVal = ((ConsoleApplication1.BPEL.ICreateOrderWS)(this)).createOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.createOrderResponse> ConsoleApplication1.BPEL.ICreateOrderWS.createOrderAsync(ConsoleApplication1.BPEL.createOrderRequest request) {
            return base.Channel.createOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.BPEL.createOrderResponse> createOrderAsync(ConsoleApplication1.BPEL.shoppingCartOrder arg0) {
            ConsoleApplication1.BPEL.createOrderRequest inValue = new ConsoleApplication1.BPEL.createOrderRequest();
            inValue.arg0 = arg0;
            return ((ConsoleApplication1.BPEL.ICreateOrderWS)(this)).createOrderAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unisell.miw.uniovi/", ConfigurationName="BPEL.IProductAvailabilityWS")]
    public interface IProductAvailabilityWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailabilityRequest", ReplyAction="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailabilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.BPEL.ProductNotAvailableException), Action="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailability/Fault/Produ" +
            "ctNotAvailableException", Name="ProductNotAvailableException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.BPEL.ArgumentException), Action="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailability/Fault/Argum" +
            "entException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.BPEL.checkAvailabilityResponse checkAvailability(ConsoleApplication1.BPEL.checkAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailabilityRequest", ReplyAction="http://ws.unisell.miw.uniovi/IProductAvailabilityWS/checkAvailabilityResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.checkAvailabilityResponse> checkAvailabilityAsync(ConsoleApplication1.BPEL.checkAvailabilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAvailability", WrapperNamespace="http://ws.unisell.miw.uniovi/", IsWrapped=true)]
    public partial class checkAvailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.BPEL.shoppingCartAvail arg0;
        
        public checkAvailabilityRequest() {
        }
        
        public checkAvailabilityRequest(ConsoleApplication1.BPEL.shoppingCartAvail arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAvailabilityResponse", WrapperNamespace="http://ws.unisell.miw.uniovi/", IsWrapped=true)]
    public partial class checkAvailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.BPEL.shoppingCartAvail @return;
        
        public checkAvailabilityResponse() {
        }
        
        public checkAvailabilityResponse(ConsoleApplication1.BPEL.shoppingCartAvail @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductAvailabilityWSChannel : ConsoleApplication1.BPEL.IProductAvailabilityWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductAvailabilityWSClient : System.ServiceModel.ClientBase<ConsoleApplication1.BPEL.IProductAvailabilityWS>, ConsoleApplication1.BPEL.IProductAvailabilityWS {
        
        public ProductAvailabilityWSClient() {
        }
        
        public ProductAvailabilityWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductAvailabilityWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAvailabilityWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAvailabilityWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.BPEL.checkAvailabilityResponse ConsoleApplication1.BPEL.IProductAvailabilityWS.checkAvailability(ConsoleApplication1.BPEL.checkAvailabilityRequest request) {
            return base.Channel.checkAvailability(request);
        }
        
        public ConsoleApplication1.BPEL.shoppingCartAvail checkAvailability(ConsoleApplication1.BPEL.shoppingCartAvail arg0) {
            ConsoleApplication1.BPEL.checkAvailabilityRequest inValue = new ConsoleApplication1.BPEL.checkAvailabilityRequest();
            inValue.arg0 = arg0;
            ConsoleApplication1.BPEL.checkAvailabilityResponse retVal = ((ConsoleApplication1.BPEL.IProductAvailabilityWS)(this)).checkAvailability(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.BPEL.checkAvailabilityResponse> ConsoleApplication1.BPEL.IProductAvailabilityWS.checkAvailabilityAsync(ConsoleApplication1.BPEL.checkAvailabilityRequest request) {
            return base.Channel.checkAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.BPEL.checkAvailabilityResponse> checkAvailabilityAsync(ConsoleApplication1.BPEL.shoppingCartAvail arg0) {
            ConsoleApplication1.BPEL.checkAvailabilityRequest inValue = new ConsoleApplication1.BPEL.checkAvailabilityRequest();
            inValue.arg0 = arg0;
            return ((ConsoleApplication1.BPEL.IProductAvailabilityWS)(this)).checkAvailabilityAsync(inValue);
        }
    }
}
