//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSell.NET.ConsoleClient.UniSellAdminWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class InvalidEntityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editUserData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private userData userDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public userData userData {
            get {
                return this.userDataField;
            }
            set {
                this.userDataField = value;
                this.RaisePropertyChanged("userData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class userData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accountEnabledField;
        
        private PersonIdDocumentType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string emailField;
        
        private string idDocumentField;
        
        private string nameField;
        
        private string passwordField;
        
        private UserRole roleField;
        
        private bool roleFieldSpecified;
        
        private string surnameField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool accountEnabled {
            get {
                return this.accountEnabledField;
            }
            set {
                this.accountEnabledField = value;
                this.RaisePropertyChanged("accountEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PersonIdDocumentType documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
                this.RaisePropertyChanged("documentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idDocument {
            get {
                return this.idDocumentField;
            }
            set {
                this.idDocumentField = value;
                this.RaisePropertyChanged("idDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public UserRole role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roleSpecified {
            get {
                return this.roleFieldSpecified;
            }
            set {
                this.roleFieldSpecified = value;
                this.RaisePropertyChanged("roleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public enum PersonIdDocumentType {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        NIF,
        
        /// <remarks/>
        NIE,
        
        /// <remarks/>
        PASSPORT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public enum UserRole {
        
        /// <remarks/>
        ADMIN,
        
        /// <remarks/>
        SELLER,
        
        /// <remarks/>
        BUYER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createAdminResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editUserData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editUserData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createAdmin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private userData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public userData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class RepeatedUsernameException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class RepeatedEmailException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class RepeatedDocumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unisell.miw.uniovi/", ConfigurationName="UniSellAdminWS.IUserAdminWS")]
    public interface IUserAdminWS {
        
        // CODEGEN: Generating message contract since the operation createAdmin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdmin/Fault/InvalidEntityExceptio" +
            "n", Name="InvalidEntityException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedUsernameException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdmin/Fault/RepeatedUsernameExcep" +
            "tion", Name="RepeatedUsernameException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedEmailException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdmin/Fault/RepeatedEmailExceptio" +
            "n", Name="RepeatedEmailException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedDocumentException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdmin/Fault/RepeatedDocumentExcep" +
            "tion", Name="RepeatedDocumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1 createAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/createAdminResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1> createAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest request);
        
        // CODEGEN: Generating message contract since the operation editAdmin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdmin/Fault/InvalidEntityException", Name="InvalidEntityException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedUsernameException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdmin/Fault/RepeatedUsernameExcepti" +
            "on", Name="RepeatedUsernameException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedEmailException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdmin/Fault/RepeatedEmailException", Name="RepeatedEmailException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.RepeatedDocumentException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdmin/Fault/RepeatedDocumentExcepti" +
            "on", Name="RepeatedDocumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1 editAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/editAdminResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1> editAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest request);
        
        // CODEGEN: Generating message contract since the operation findAdmin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/findAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/findAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellAdminWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/IUserAdminWS/findAdmin/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1 findAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/IUserAdminWS/findAdminRequest", ReplyAction="http://ws.unisell.miw.uniovi/IUserAdminWS/findAdminResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1> findAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binarySecurityTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BinarySecurityToken {
            get {
                return this.binarySecurityTokenField;
            }
            set {
                this.binarySecurityTokenField = value;
                this.RaisePropertyChanged("BinarySecurityToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdminRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.createAdmin createAdmin;
        
        public createAdminRequest() {
        }
        
        public createAdminRequest(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.createAdmin createAdmin) {
            this.arg0 = arg0;
            this.createAdmin = createAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdminResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse createAdminResponse;
        
        public createAdminResponse1() {
        }
        
        public createAdminResponse1(UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse createAdminResponse) {
            this.createAdminResponse = createAdminResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editAdmin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editUserData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editUserData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editAdminResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editUserData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editUserData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editAdminRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.editAdmin editAdmin;
        
        public editAdminRequest() {
        }
        
        public editAdminRequest(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.editAdmin editAdmin) {
            this.arg0 = arg0;
            this.editAdmin = editAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editAdminResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse editAdminResponse;
        
        public editAdminResponse1() {
        }
        
        public editAdminResponse1(UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse editAdminResponse) {
            this.editAdminResponse = editAdminResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findAdmin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
                this.RaisePropertyChanged("arg1Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findAdminResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editUserData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editUserData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAdminRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.findAdmin findAdmin;
        
        public findAdminRequest() {
        }
        
        public findAdminRequest(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.findAdmin findAdmin) {
            this.arg0 = arg0;
            this.findAdmin = findAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findAdminResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse findAdminResponse;
        
        public findAdminResponse1() {
        }
        
        public findAdminResponse1(UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse findAdminResponse) {
            this.findAdminResponse = findAdminResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAdminWSChannel : UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAdminWSClient : System.ServiceModel.ClientBase<UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS>, UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS {
        
        public UserAdminWSClient() {
        }
        
        public UserAdminWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAdminWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAdminWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAdminWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1 UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.createAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest request) {
            return base.Channel.createAdmin(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse createAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.createAdmin createAdmin1) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest();
            inValue.arg0 = arg0;
            inValue.createAdmin = createAdmin1;
            UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).createAdmin(inValue);
            return retVal.createAdminResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1> UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.createAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest request) {
            return base.Channel.createAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminResponse1> createAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.createAdmin createAdmin) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.createAdminRequest();
            inValue.arg0 = arg0;
            inValue.createAdmin = createAdmin;
            return ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).createAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1 UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.editAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest request) {
            return base.Channel.editAdmin(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse editAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.editAdmin editAdmin1) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest();
            inValue.arg0 = arg0;
            inValue.editAdmin = editAdmin1;
            UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).editAdmin(inValue);
            return retVal.editAdminResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1> UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.editAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest request) {
            return base.Channel.editAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminResponse1> editAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.editAdmin editAdmin) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.editAdminRequest();
            inValue.arg0 = arg0;
            inValue.editAdmin = editAdmin;
            return ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).editAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1 UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.findAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest request) {
            return base.Channel.findAdmin(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse findAdmin(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.findAdmin findAdmin1) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest();
            inValue.arg0 = arg0;
            inValue.findAdmin = findAdmin1;
            UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).findAdmin(inValue);
            return retVal.findAdminResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1> UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS.findAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest request) {
            return base.Channel.findAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminResponse1> findAdminAsync(UniSell.NET.ConsoleClient.UniSellAdminWS.Security arg0, UniSell.NET.ConsoleClient.UniSellAdminWS.findAdmin findAdmin) {
            UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest inValue = new UniSell.NET.ConsoleClient.UniSellAdminWS.findAdminRequest();
            inValue.arg0 = arg0;
            inValue.findAdmin = findAdmin;
            return ((UniSell.NET.ConsoleClient.UniSellAdminWS.IUserAdminWS)(this)).findAdminAsync(inValue);
        }
    }
}
