//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSell.NET.ConsoleClient.UniSellCompanyWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public partial class LocationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class companyData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string idDocumentField;
        
        private LegalPersonIdDocumentType idDocumentTypeField;
        
        private bool idDocumentTypeFieldSpecified;
        
        private LocationInfo locationInfoField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idDocument {
            get {
                return this.idDocumentField;
            }
            set {
                this.idDocumentField = value;
                this.RaisePropertyChanged("idDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LegalPersonIdDocumentType idDocumentType {
            get {
                return this.idDocumentTypeField;
            }
            set {
                this.idDocumentTypeField = value;
                this.RaisePropertyChanged("idDocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDocumentTypeSpecified {
            get {
                return this.idDocumentTypeFieldSpecified;
            }
            set {
                this.idDocumentTypeFieldSpecified = value;
                this.RaisePropertyChanged("idDocumentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public LocationInfo locationInfo {
            get {
                return this.locationInfoField;
            }
            set {
                this.locationInfoField = value;
                this.RaisePropertyChanged("locationInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public enum LegalPersonIdDocumentType {
        
        /// <remarks/>
        CIF,
        
        /// <remarks/>
        CIE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCompanyData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private companyData companyDataField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public companyData companyData {
            get {
                return this.companyDataField;
            }
            set {
                this.companyDataField = value;
                this.RaisePropertyChanged("companyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findCompanyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCompanyData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCompanyData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findCompany : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
                this.RaisePropertyChanged("arg1Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ElementNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class CannotRemoveElementException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class RepeatedDocumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class InvalidEntityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class UnauthorizeAccessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unisell.miw.uniovi/", ConfigurationName="UniSellCompanyWS.ICompanyWS")]
    public interface ICompanyWS {
        
        // CODEGEN: Generating message contract since the operation findCompany is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/findCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/findCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/findCompany/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1 findCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/findCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/findCompanyResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1> findCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest request);
        
        // CODEGEN: Generating message contract since the operation removeCompany is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompany/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.ElementNotFoundException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompany/Fault/ElementNotFoundExcept" +
            "ion", Name="ElementNotFoundException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.CannotRemoveElementException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompany/Fault/CannotRemoveElementEx" +
            "ception", Name="CannotRemoveElementException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1 removeCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/removeCompanyResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1> removeCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest request);
        
        // CODEGEN: Generating message contract since the operation editCompany is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/editCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/editCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.RepeatedDocumentException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/editCompany/Fault/RepeatedDocumentExcepti" +
            "on", Name="RepeatedDocumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/editCompany/Fault/InvalidEntityException", Name="InvalidEntityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1 editCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/editCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/editCompanyResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1> editCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest request);
        
        // CODEGEN: Generating message contract since the operation createCompany is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/createCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/createCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.RepeatedDocumentException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/createCompany/Fault/RepeatedDocumentExcep" +
            "tion", Name="RepeatedDocumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/createCompany/Fault/InvalidEntityExceptio" +
            "n", Name="InvalidEntityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1 createCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/createCompanyRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/createCompanyResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1> createCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest request);
        
        // CODEGEN: Generating message contract since the operation listCompaniesByFilter is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilterRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.UnauthorizeAccessException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilter/Fault/UnauthorizeAc" +
            "cessException", Name="UnauthorizeAccessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCompanyWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilter/Fault/ArgumentExcep" +
            "tion", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse listCompaniesByFilter(UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilterRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICompanyWS/listCompaniesByFilterResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse> listCompaniesByFilterAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binarySecurityTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BinarySecurityToken {
            get {
                return this.binarySecurityTokenField;
            }
            set {
                this.binarySecurityTokenField = value;
                this.RaisePropertyChanged("BinarySecurityToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompany findCompany;
        
        public findCompanyRequest() {
        }
        
        public findCompanyRequest(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompany findCompany) {
            this.arg0 = arg0;
            this.findCompany = findCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCompanyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse findCompanyResponse;
        
        public findCompanyResponse1() {
        }
        
        public findCompanyResponse1(UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse findCompanyResponse) {
            this.findCompanyResponse = findCompanyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class removeCompany : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
                this.RaisePropertyChanged("arg1Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class removeCompanyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCompanyData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCompanyData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompany removeCompany;
        
        public removeCompanyRequest() {
        }
        
        public removeCompanyRequest(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompany removeCompany) {
            this.arg0 = arg0;
            this.removeCompany = removeCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeCompanyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse removeCompanyResponse;
        
        public removeCompanyResponse1() {
        }
        
        public removeCompanyResponse1(UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse removeCompanyResponse) {
            this.removeCompanyResponse = removeCompanyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCompany : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCompanyData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCompanyData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCompanyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCompanyData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCompanyData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompany editCompany;
        
        public editCompanyRequest() {
        }
        
        public editCompanyRequest(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompany editCompany) {
            this.arg0 = arg0;
            this.editCompany = editCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCompanyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse editCompanyResponse;
        
        public editCompanyResponse1() {
        }
        
        public editCompanyResponse1(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse editCompanyResponse) {
            this.editCompanyResponse = editCompanyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createCompany : object, System.ComponentModel.INotifyPropertyChanged {
        
        private companyData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public companyData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createCompanyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCompanyData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCompanyData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompany createCompany;
        
        public createCompanyRequest() {
        }
        
        public createCompanyRequest(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompany createCompany) {
            this.arg0 = arg0;
            this.createCompany = createCompany;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createCompanyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse createCompanyResponse;
        
        public createCompanyResponse1() {
        }
        
        public createCompanyResponse1(UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse createCompanyResponse) {
            this.createCompanyResponse = createCompanyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class listCompaniesByFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompanySearchFilter arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CompanySearchFilter arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public partial class CompanySearchFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idDocumentField;
        
        private string idDocumentTypeField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdDocument {
            get {
                return this.idDocumentField;
            }
            set {
                this.idDocumentField = value;
                this.RaisePropertyChanged("IdDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdDocumentType {
            get {
                return this.idDocumentTypeField;
            }
            set {
                this.idDocumentTypeField = value;
                this.RaisePropertyChanged("IdDocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listCompaniesByFilterRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilter listCompaniesByFilter;
        
        public listCompaniesByFilterRequest() {
        }
        
        public listCompaniesByFilterRequest(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilter listCompaniesByFilter) {
            this.arg0 = arg0;
            this.listCompaniesByFilter = listCompaniesByFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listCompaniesByFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listCompaniesByFilterResponse", Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyData[] listCompaniesByFilterResponse1;
        
        public listCompaniesByFilterResponse() {
        }
        
        public listCompaniesByFilterResponse(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyData[] listCompaniesByFilterResponse1) {
            this.listCompaniesByFilterResponse1 = listCompaniesByFilterResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyWSChannel : UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyWSClient : System.ServiceModel.ClientBase<UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS>, UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS {
        
        public CompanyWSClient() {
        }
        
        public CompanyWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1 UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.findCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest request) {
            return base.Channel.findCompany(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse findCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompany findCompany1) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest();
            inValue.arg0 = arg0;
            inValue.findCompany = findCompany1;
            UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).findCompany(inValue);
            return retVal.findCompanyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1> UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.findCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest request) {
            return base.Channel.findCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyResponse1> findCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompany findCompany) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.findCompanyRequest();
            inValue.arg0 = arg0;
            inValue.findCompany = findCompany;
            return ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).findCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1 UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.removeCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest request) {
            return base.Channel.removeCompany(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse removeCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompany removeCompany1) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest();
            inValue.arg0 = arg0;
            inValue.removeCompany = removeCompany1;
            UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).removeCompany(inValue);
            return retVal.removeCompanyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1> UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.removeCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest request) {
            return base.Channel.removeCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyResponse1> removeCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompany removeCompany) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.removeCompanyRequest();
            inValue.arg0 = arg0;
            inValue.removeCompany = removeCompany;
            return ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).removeCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1 UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.editCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest request) {
            return base.Channel.editCompany(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse editCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompany editCompany1) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest();
            inValue.arg0 = arg0;
            inValue.editCompany = editCompany1;
            UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).editCompany(inValue);
            return retVal.editCompanyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1> UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.editCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest request) {
            return base.Channel.editCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyResponse1> editCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompany editCompany) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyRequest();
            inValue.arg0 = arg0;
            inValue.editCompany = editCompany;
            return ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).editCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1 UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.createCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest request) {
            return base.Channel.createCompany(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse createCompany(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompany createCompany1) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest();
            inValue.arg0 = arg0;
            inValue.createCompany = createCompany1;
            UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).createCompany(inValue);
            return retVal.createCompanyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1> UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.createCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest request) {
            return base.Channel.createCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyResponse1> createCompanyAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompany createCompany) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.createCompanyRequest();
            inValue.arg0 = arg0;
            inValue.createCompany = createCompany;
            return ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).createCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.listCompaniesByFilter(UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest request) {
            return base.Channel.listCompaniesByFilter(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCompanyWS.editCompanyData[] listCompaniesByFilter(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilter listCompaniesByFilter1) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest();
            inValue.arg0 = arg0;
            inValue.listCompaniesByFilter = listCompaniesByFilter1;
            UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse retVal = ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).listCompaniesByFilter(inValue);
            return retVal.listCompaniesByFilterResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse> UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS.listCompaniesByFilterAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest request) {
            return base.Channel.listCompaniesByFilterAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterResponse> listCompaniesByFilterAsync(UniSell.NET.ConsoleClient.UniSellCompanyWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilter listCompaniesByFilter) {
            UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest inValue = new UniSell.NET.ConsoleClient.UniSellCompanyWS.listCompaniesByFilterRequest();
            inValue.arg0 = arg0;
            inValue.listCompaniesByFilter = listCompaniesByFilter;
            return ((UniSell.NET.ConsoleClient.UniSellCompanyWS.ICompanyWS)(this)).listCompaniesByFilterAsync(inValue);
        }
    }
}
