
package uniovi.miw.unisell.data;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentityWS", targetNamespace = "http://unisell.net.data/", wsdlLocation = "http://localhost:9090/WebServices/IdentityWS.asmx?WSDL")
public class IdentityWS
    extends Service
{

    private final static URL IDENTITYWS_WSDL_LOCATION;
    private final static WebServiceException IDENTITYWS_EXCEPTION;
    private final static QName IDENTITYWS_QNAME = new QName("http://unisell.net.data/", "IdentityWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/WebServices/IdentityWS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYWS_WSDL_LOCATION = url;
        IDENTITYWS_EXCEPTION = e;
    }

    public IdentityWS() {
        super(__getWsdlLocation(), IDENTITYWS_QNAME);
    }

    public IdentityWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYWS_QNAME, features);
    }

    public IdentityWS(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYWS_QNAME);
    }

    public IdentityWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYWS_QNAME, features);
    }

    public IdentityWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentityWSSoap
     */
    @WebEndpoint(name = "IdentityWSSoap")
    public IdentityWSSoap getIdentityWSSoap() {
        return super.getPort(new QName("http://unisell.net.data/", "IdentityWSSoap"), IdentityWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentityWSSoap
     */
    @WebEndpoint(name = "IdentityWSSoap")
    public IdentityWSSoap getIdentityWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://unisell.net.data/", "IdentityWSSoap"), IdentityWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns IdentityWSSoap
     */
    @WebEndpoint(name = "IdentityWSSoap12")
    public IdentityWSSoap getIdentityWSSoap12() {
        return super.getPort(new QName("http://unisell.net.data/", "IdentityWSSoap12"), IdentityWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentityWSSoap
     */
    @WebEndpoint(name = "IdentityWSSoap12")
    public IdentityWSSoap getIdentityWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://unisell.net.data/", "IdentityWSSoap12"), IdentityWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYWS_EXCEPTION!= null) {
            throw IDENTITYWS_EXCEPTION;
        }
        return IDENTITYWS_WSDL_LOCATION;
    }

}
