
package uniovi.miw.unisell.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdentityWSSoap", targetNamespace = "http://unisell.net.data/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdentityWSSoap {


    /**
     * 
     * @param security
     * @return
     *     returns uniovi.miw.unisell.data.IdentityData
     */
    @WebMethod(operationName = "GetIdentity", action = "http://unisell.net.data/GetIdentity")
    @WebResult(name = "GetIdentityResult", targetNamespace = "http://unisell.net.data/")
    @RequestWrapper(localName = "GetIdentity", targetNamespace = "http://unisell.net.data/", className = "uniovi.miw.unisell.data.GetIdentity")
    @ResponseWrapper(localName = "GetIdentityResponse", targetNamespace = "http://unisell.net.data/", className = "uniovi.miw.unisell.data.GetIdentityResponse")
    public IdentityData getIdentity(
        @WebParam(name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/04/secext", header = true, partName = "Security")
        Security security);

}
