//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIW.Bot.WebApi.identityWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://unisell.net.data/", ConfigurationName="identityWS.IdentityWSSoap")]
    public interface IdentityWSSoap {
        
        // CODEGEN: Generating message contract since message GetIdentityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://unisell.net.data/GetIdentity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIW.Bot.WebApi.identityWS.GetIdentityResponse GetIdentity(MIW.Bot.WebApi.identityWS.GetIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://unisell.net.data/GetIdentity", ReplyAction="*")]
        System.Threading.Tasks.Task<MIW.Bot.WebApi.identityWS.GetIdentityResponse> GetIdentityAsync(MIW.Bot.WebApi.identityWS.GetIdentityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binarySecurityTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BinarySecurityToken {
            get {
                return this.binarySecurityTokenField;
            }
            set {
                this.binarySecurityTokenField = value;
                this.RaisePropertyChanged("BinarySecurityToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public partial class IdentityData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private UserRole roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UserRole Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://unisell.net.data/")]
    public enum UserRole {
        
        /// <remarks/>
        ADMIN,
        
        /// <remarks/>
        SELLER,
        
        /// <remarks/>
        BUYER,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIdentity", WrapperNamespace="http://unisell.net.data/", IsWrapped=true)]
    public partial class GetIdentityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        public MIW.Bot.WebApi.identityWS.Security Security;
        
        public GetIdentityRequest() {
        }
        
        public GetIdentityRequest(MIW.Bot.WebApi.identityWS.Security Security) {
            this.Security = Security;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIdentityResponse", WrapperNamespace="http://unisell.net.data/", IsWrapped=true)]
    public partial class GetIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://unisell.net.data/", Order=0)]
        public MIW.Bot.WebApi.identityWS.IdentityData GetIdentityResult;
        
        public GetIdentityResponse() {
        }
        
        public GetIdentityResponse(MIW.Bot.WebApi.identityWS.IdentityData GetIdentityResult) {
            this.GetIdentityResult = GetIdentityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdentityWSSoapChannel : MIW.Bot.WebApi.identityWS.IdentityWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdentityWSSoapClient : System.ServiceModel.ClientBase<MIW.Bot.WebApi.identityWS.IdentityWSSoap>, MIW.Bot.WebApi.identityWS.IdentityWSSoap {
        
        public IdentityWSSoapClient() {
        }
        
        public IdentityWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdentityWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIW.Bot.WebApi.identityWS.GetIdentityResponse MIW.Bot.WebApi.identityWS.IdentityWSSoap.GetIdentity(MIW.Bot.WebApi.identityWS.GetIdentityRequest request) {
            return base.Channel.GetIdentity(request);
        }
        
        public MIW.Bot.WebApi.identityWS.IdentityData GetIdentity(MIW.Bot.WebApi.identityWS.Security Security) {
            MIW.Bot.WebApi.identityWS.GetIdentityRequest inValue = new MIW.Bot.WebApi.identityWS.GetIdentityRequest();
            inValue.Security = Security;
            MIW.Bot.WebApi.identityWS.GetIdentityResponse retVal = ((MIW.Bot.WebApi.identityWS.IdentityWSSoap)(this)).GetIdentity(inValue);
            return retVal.GetIdentityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MIW.Bot.WebApi.identityWS.GetIdentityResponse> MIW.Bot.WebApi.identityWS.IdentityWSSoap.GetIdentityAsync(MIW.Bot.WebApi.identityWS.GetIdentityRequest request) {
            return base.Channel.GetIdentityAsync(request);
        }
        
        public System.Threading.Tasks.Task<MIW.Bot.WebApi.identityWS.GetIdentityResponse> GetIdentityAsync(MIW.Bot.WebApi.identityWS.Security Security) {
            MIW.Bot.WebApi.identityWS.GetIdentityRequest inValue = new MIW.Bot.WebApi.identityWS.GetIdentityRequest();
            inValue.Security = Security;
            return ((MIW.Bot.WebApi.identityWS.IdentityWSSoap)(this)).GetIdentityAsync(inValue);
        }
    }
}
