//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSell.NET.ConsoleClient.UniSellCategoryWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class UnauthorizeAccessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class categoryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCategoryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoryData categoryDataField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoryData categoryData {
            get {
                return this.categoryDataField;
            }
            set {
                this.categoryDataField = value;
                this.RaisePropertyChanged("categoryData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class listCategoriesByName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class RepeatedNameException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class InvalidEntityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class ElementNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class CannotRemoveElementException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unisell.miw.uniovi/", ConfigurationName="UniSellCategoryWS.ICategoryWS")]
    public interface ICategoryWS {
        
        // CODEGEN: Generating message contract since the operation listCategoriesByName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/listCategoriesByNameRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/listCategoriesByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.UnauthorizeAccessException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/listCategoriesByName/Fault/UnauthorizeAc" +
            "cessException", Name="UnauthorizeAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse listCategoriesByName(UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/listCategoriesByNameRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/listCategoriesByNameResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse> listCategoriesByNameAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest request);
        
        // CODEGEN: Generating message contract since the operation findCategory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/findCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/findCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/findCategory/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1 findCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/findCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/findCategoryResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1> findCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest request);
        
        // CODEGEN: Generating message contract since the operation editCategory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/editCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/editCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.RepeatedNameException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/editCategory/Fault/RepeatedNameException" +
            "", Name="RepeatedNameException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/editCategory/Fault/InvalidEntityExceptio" +
            "n", Name="InvalidEntityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1 editCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/editCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/editCategoryResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1> editCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest request);
        
        // CODEGEN: Generating message contract since the operation createCategory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/createCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/createCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.RepeatedNameException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/createCategory/Fault/RepeatedNameExcepti" +
            "on", Name="RepeatedNameException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.InvalidEntityException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/createCategory/Fault/InvalidEntityExcept" +
            "ion", Name="InvalidEntityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1 createCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/createCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/createCategoryResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1> createCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest request);
        
        // CODEGEN: Generating message contract since the operation removeCategory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.ArgumentException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategory/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.ElementNotFoundException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategory/Fault/ElementNotFoundExce" +
            "ption", Name="ElementNotFoundException")]
        [System.ServiceModel.FaultContractAttribute(typeof(UniSell.NET.ConsoleClient.UniSellCategoryWS.CannotRemoveElementException), Action="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategory/Fault/CannotRemoveElement" +
            "Exception", Name="CannotRemoveElementException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1 removeCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategoryRequest", ReplyAction="http://ws.unisell.miw.uniovi/ICategoryWS/removeCategoryResponse")]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1> removeCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
    public partial class Security : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binarySecurityTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BinarySecurityToken {
            get {
                return this.binarySecurityTokenField;
            }
            set {
                this.binarySecurityTokenField = value;
                this.RaisePropertyChanged("BinarySecurityToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listCategoriesByNameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByName listCategoriesByName;
        
        public listCategoriesByNameRequest() {
        }
        
        public listCategoriesByNameRequest(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByName listCategoriesByName) {
            this.arg0 = arg0;
            this.listCategoriesByName = listCategoriesByName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listCategoriesByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listCategoriesByNameResponse", Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryData[] listCategoriesByNameResponse1;
        
        public listCategoriesByNameResponse() {
        }
        
        public listCategoriesByNameResponse(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryData[] listCategoriesByNameResponse1) {
            this.listCategoriesByNameResponse1 = listCategoriesByNameResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
                this.RaisePropertyChanged("arg1Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class findCategoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCategoryData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCategoryData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCategoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategory findCategory;
        
        public findCategoryRequest() {
        }
        
        public findCategoryRequest(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategory findCategory) {
            this.arg0 = arg0;
            this.findCategory = findCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findCategoryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse findCategoryResponse;
        
        public findCategoryResponse1() {
        }
        
        public findCategoryResponse1(UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse findCategoryResponse) {
            this.findCategoryResponse = findCategoryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCategoryData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCategoryData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class editCategoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCategoryData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCategoryData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCategoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategory editCategory;
        
        public editCategoryRequest() {
        }
        
        public editCategoryRequest(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategory editCategory) {
            this.arg0 = arg0;
            this.editCategory = editCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCategoryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse editCategoryResponse;
        
        public editCategoryResponse1() {
        }
        
        public editCategoryResponse1(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse editCategoryResponse) {
            this.editCategoryResponse = editCategoryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoryData arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoryData arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class createCategoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCategoryData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCategoryData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createCategoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategory createCategory;
        
        public createCategoryRequest() {
        }
        
        public createCategoryRequest(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategory createCategory) {
            this.arg0 = arg0;
            this.createCategory = createCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createCategoryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse createCategoryResponse;
        
        public createCategoryResponse1() {
        }
        
        public createCategoryResponse1(UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse createCategoryResponse) {
            this.createCategoryResponse = createCategoryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class removeCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
                this.RaisePropertyChanged("arg1Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.unisell.miw.uniovi/")]
    public partial class removeCategoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private editCategoryData returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public editCategoryData @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeCategoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/04/secext")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategory removeCategory;
        
        public removeCategoryRequest() {
        }
        
        public removeCategoryRequest(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategory removeCategory) {
            this.arg0 = arg0;
            this.removeCategory = removeCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeCategoryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.unisell.miw.uniovi/", Order=0)]
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse removeCategoryResponse;
        
        public removeCategoryResponse1() {
        }
        
        public removeCategoryResponse1(UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse removeCategoryResponse) {
            this.removeCategoryResponse = removeCategoryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryWSChannel : UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryWSClient : System.ServiceModel.ClientBase<UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS>, UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS {
        
        public CategoryWSClient() {
        }
        
        public CategoryWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.listCategoriesByName(UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest request) {
            return base.Channel.listCategoriesByName(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryData[] listCategoriesByName(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByName listCategoriesByName1) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest();
            inValue.arg0 = arg0;
            inValue.listCategoriesByName = listCategoriesByName1;
            UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse retVal = ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).listCategoriesByName(inValue);
            return retVal.listCategoriesByNameResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse> UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.listCategoriesByNameAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest request) {
            return base.Channel.listCategoriesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameResponse> listCategoriesByNameAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByName listCategoriesByName) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.listCategoriesByNameRequest();
            inValue.arg0 = arg0;
            inValue.listCategoriesByName = listCategoriesByName;
            return ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).listCategoriesByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1 UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.findCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest request) {
            return base.Channel.findCategory(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse findCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategory findCategory1) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest();
            inValue.arg0 = arg0;
            inValue.findCategory = findCategory1;
            UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).findCategory(inValue);
            return retVal.findCategoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1> UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.findCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest request) {
            return base.Channel.findCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryResponse1> findCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategory findCategory) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.findCategoryRequest();
            inValue.arg0 = arg0;
            inValue.findCategory = findCategory;
            return ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).findCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1 UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.editCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest request) {
            return base.Channel.editCategory(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse editCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategory editCategory1) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest();
            inValue.arg0 = arg0;
            inValue.editCategory = editCategory1;
            UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).editCategory(inValue);
            return retVal.editCategoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1> UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.editCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest request) {
            return base.Channel.editCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryResponse1> editCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategory editCategory) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.editCategoryRequest();
            inValue.arg0 = arg0;
            inValue.editCategory = editCategory;
            return ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).editCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1 UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.createCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest request) {
            return base.Channel.createCategory(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse createCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategory createCategory1) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest();
            inValue.arg0 = arg0;
            inValue.createCategory = createCategory1;
            UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).createCategory(inValue);
            return retVal.createCategoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1> UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.createCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest request) {
            return base.Channel.createCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryResponse1> createCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategory createCategory) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.createCategoryRequest();
            inValue.arg0 = arg0;
            inValue.createCategory = createCategory;
            return ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).createCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1 UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.removeCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest request) {
            return base.Channel.removeCategory(request);
        }
        
        public UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse removeCategory(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategory removeCategory1) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest();
            inValue.arg0 = arg0;
            inValue.removeCategory = removeCategory1;
            UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1 retVal = ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).removeCategory(inValue);
            return retVal.removeCategoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1> UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS.removeCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest request) {
            return base.Channel.removeCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryResponse1> removeCategoryAsync(UniSell.NET.ConsoleClient.UniSellCategoryWS.Security arg0, UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategory removeCategory) {
            UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest inValue = new UniSell.NET.ConsoleClient.UniSellCategoryWS.removeCategoryRequest();
            inValue.arg0 = arg0;
            inValue.removeCategory = removeCategory;
            return ((UniSell.NET.ConsoleClient.UniSellCategoryWS.ICategoryWS)(this)).removeCategoryAsync(inValue);
        }
    }
}
